In [38]:
import numpy
import string

def reverse(arr):
    start = 0; end = len(arr) - 1
    while start < end:
        arr[start], arr[end] = arr[end], arr[start]
        start +=1; end -= 1
    
    

matrix = [[5,1,9,11],[2,4,8,10],[13,3,6,7],[15,14,12,16]]
print("Before transpose")
print(numpy.matrix(matrix), end="\n\n")

n = len(matrix[0])

for i in range(n):
    for j in range(i, n):
        matrix[i][j], matrix[j][i] = matrix[j][i], matrix[i][j]

print("After transpose")
print(numpy.matrix(matrix), end="\n\n")

for row in matrix:
    reverse(row)

print("After rotation")
print(numpy.matrix(matrix), end="\n\n")

print(string.ascii_lowercase[0])

Before transpose
[[ 5  1  9 11]
 [ 2  4  8 10]
 [13  3  6  7]
 [15 14 12 16]]

After transpose
[[ 5  2 13 15]
 [ 1  4  3 14]
 [ 9  8  6 12]
 [11 10  7 16]]

After rotation
[[15 13  2  5]
 [14  3  4  1]
 [12  6  8  9]
 [16  7 10 11]]

a


In [47]:
class Solution:
    def exist(self, board: List[List[str]], word: str) -> int:
        self.board = board
        self.rowLength = len(board)
        self.colLength = len(board[0])
    
        count = 0
        for i in range(self.rowLength):
            for j in range(self.colLength):
                if board[i][j] == word[0] and self.search(word, i, j, 0):
                    count =+ 1
        return count
    
    def search(self, word, row, col, index):
        if index == len(word) - 1:
            return True
        character = self.board[row][col]
        self.board[row][col] = "$"
        
        if row < self.rowLength - 1 and self.board[row + 1][col] == word[index + 1] and self.search(word, row + 1, col, index + 1):
            return True
        if col < self.colLength - 1 and self.board[row][col + 1] == word[index + 1] and self.search(word, row, col + 1, index + 1):
            return True
        if row > 0 and self.board[row - 1][col] == word[index + 1] and self.search(word, row - 1, col, index + 1):
            return True
        if col > 0 and self.board[row][col-1] == word[index + 1] and self.search(word, row, col-1, index + 1):
            return True
        
        self.board[row][col] = character
        
        return False
A = [
  ['s', 'o', 's', 'o'],
  ['s', 'o', 'o', 's'],
  ['s', 's', 's', 's']
]    
Solution().exist(A,"sos")

1