> **Reconstruction Solution**

 - A robot is located at the top-left corner of a m x n grid (marked 'S' in the diagram below). The robot can only move either dow or right at any point in time. The robot is trying to reach the bottom-right corner of the grid (marked 'E' in the diagram below).
 <br>
 How many possible unique paths are there?
 <br>
 <br>
 
 ```json
	+---+---+---+---+
	| S |   |   |   |
	+---+---+---+---+
	|   |   |   |   |
	+---+---+---+---+
	|   |   |   | E |
	+---+---+---+---+
    ```
    
	Above is a 3 x 4 grid. How many possible unique paths are there?


 
 <br>
 <br>
 
 _**Framework for solving DP problems :**_
 1. Define the objective function
     - f(i) is the number of distinct ways to reach the i-th stairs
 2. Identity base cases
     - $F(0,0) = 1$
 3. write down a recurrence relation (transition function) for the optimised objective function
     - $ F(i,j) = max(F(i-1, j), F(i, j-1)) $
 4. What's the order of execution ?
     - Bottom Up approach
 5. Where to look for the answer
     - f(n)
         
 <br>
 <br>
 
_Time complexity: O(N) | Space complexity: O(N)_


In [27]:
from typing import List
import numpy as np

"""
𝐹(𝑖,𝑗)=𝑚𝑎𝑥(𝐹(𝑖−1,𝑗),𝐹(𝑖,𝑗−1))
"""
def uniquePaths(m: int, n: int) -> int:
    dp = [[0 for _ in range(n)] for _ in range(m)]
    dp[0][0] = 1
    
    print(np.matrix(dp), end= "\n\n")
    for i in range(m):
        for j in range(n):
            if i > 0 and j > 0:
                dp[i][j] = dp[i - 1][j] + dp[i][j-1]
            elif i > 0 and j == 0:
                dp[i][j] = dp[i - 1][j]
            elif j > 0 and i == 0:
                dp[i][j] = dp[i][j-1]
    print(np.matrix(dp))
    return dp[m-1][n-1]

import unittest
class StairClimberTest(unittest.TestCase):
    def test_uniquePaths(self):
        result = uniquePaths(1,1)
        self.assertEqual(result, 1)
        
    def test_uniquePaths(self):
        result = uniquePaths(3,4)
        self.assertEqual(result, 10)

unittest.main(argv=[''], verbosity=2, exit=False)

test_uniquePaths (__main__.StairClimberTest) ... <ipython-input-27-a6019e682441>:11: PendingDeprecationWarning: the matrix subclass is not the recommended way to represent matrices or deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Please adjust your code to use regular ndarray.
  print(np.matrix(dp), end= "\n\n")
<ipython-input-27-a6019e682441>:20: PendingDeprecationWarning: the matrix subclass is not the recommended way to represent matrices or deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Please adjust your code to use regular ndarray.
  print(np.matrix(dp))
ok
test_uniquePaths (__main__.UniquePathObstacle) ... 

[[1 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

[[ 1  1  1  1]
 [ 1  2  3  4]
 [ 1  3  6 10]]


FAIL

FAIL: test_uniquePaths (__main__.UniquePathObstacle)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<ipython-input-26-e7538888dd31>", line 48, in test_uniquePaths
    self.assertEqual(result, 10)
AssertionError: 2 != 10

----------------------------------------------------------------------
Ran 2 tests in 0.005s

FAILED (failures=1)


> **Unique Paths with Obstales**

 - A robot is located at the top-left corner of a m x n grid (marked 'S' in the diagram below).
 The robot can only move either down or right at any point in time.The robot is trying to reach the bottom-right corner of the grid (marked 'E' in the diagram below).
 <br>
	Now consider if some obstacles are added to the grids.
    How many unique paths would there be?
 <br>
 <br>
 
 ```json
	+---+---+---+---+
	| S |   |   |   |
	+---+---+---+---+
	|   | 1 | 1 | 1 |
	+---+---+---+---+
	|   |   |   | E |
	+---+---+---+---+
    ```
    
An obstacle and empty space is marked as 1 and 0 respectively in the grid.


 
 <br>
 <br>
 
 _**Framework for solving DP problems :**_
 1. Define the objective function
     - f(i) is the number of distinct ways to reach the i-th stairs
 2. Identity base cases
     - $F(0,0) = 1$
 3. write down a recurrence relation (transition function) for the optimised objective function
     - $ F(i,j) = max(F(i-1, j), F(i, j-1)) $
 4. What's the order of execution ?
     - Bottom Up approach
 5. Where to look for the answer
     - f(n)
         
 <br>
 <br>
 
_Time complexity: O(N) | Space complexity: O(N)_


In [32]:
from typing import List
import numpy as np

"""
𝐹(𝑖,𝑗)=𝑚𝑎𝑥(𝐹(𝑖−1,𝑗),𝐹(𝑖,𝑗−1))
"""
def uniquePaths_obstacle(grid: List[List[int]]) -> int:
    m = len(grid)
    n = len(grid[0])
    
    dp = [[0 for _ in range(n)] for _ in range(m)]
    dp[0][0] = 1
    
#     print(np.matrix(dp), end= "\n\n")
    for i in range(m):
        for j in range(n):
            if grid[i][j] == 1:
                dp[i][j] = 0
                continue
                
            if i > 0 and j > 0:
                dp[i][j] = dp[i - 1][j] + dp[i][j-1]
            elif i > 0 and j == 0:
                dp[i][j] = dp[i - 1][j]
            elif j > 0 and i == 0:
                dp[i][j] = dp[i][j-1]
#     print(np.matrix(dp))
    return dp[m-1][n-1]

import unittest
class UniquePathObstacle(unittest.TestCase):
    def test_uniquePaths4(self):
        maxtrix = [
            [0, 0, 0, 0],
            [0, 0, 1, 1],
            [0, 0, 0, 0]        
         ]
        result = uniquePaths_obstacle(maxtrix)
        self.assertEqual(result, 3)
        
    def test_uniquePaths2(self):
        maxtrix = [
            [0, 1, 0, 0],
            [0, 0, 1, 1],
            [0, 0, 0, 0]        
         ]
        result = uniquePaths_obstacle(maxtrix)
        self.assertEqual(result, 2)

unittest.main(argv=[''], verbosity=2, exit=False)

test_uniquePaths (__main__.StairClimberTest) ... <ipython-input-27-a6019e682441>:11: PendingDeprecationWarning: the matrix subclass is not the recommended way to represent matrices or deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Please adjust your code to use regular ndarray.
  print(np.matrix(dp), end= "\n\n")
<ipython-input-27-a6019e682441>:20: PendingDeprecationWarning: the matrix subclass is not the recommended way to represent matrices or deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Please adjust your code to use regular ndarray.
  print(np.matrix(dp))
ok
test_uniquePaths2 (__main__.UniquePathObstacle) ... ok
test_uniquePaths4 (__main__.UniquePathObstacle) ... 

[[1 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

[[ 1  1  1  1]
 [ 1  2  3  4]
 [ 1  3  6 10]]


ok

----------------------------------------------------------------------
Ran 3 tests in 0.005s

OK
