>**Longest Common Subsequence**  


- [Longest Common Subsequence](https://www.youtube.com/watch?v=PyGSxBbzG0Q&list=PLt4nG7RVVk1jcoLFb1gn0EylZ381IgrNq&index=6&ab_channel=CodingSimplified)
- [Longest common subsequence](https://www.youtube.com/watch?v=LAKWWDX3sGw&list=PLEJXowNB4kPxBwaXtRO1qFLpCzF75DYrS&index=19&ab_channel=TECHDOSE)

Solution using DP tabulation:

    if m == 0 or n == 0:
        return 0
    else if S1[m - 1] == S2[n-1]:
        return 1 + lcs(S1, S2, m-1, n-1)
    else
        return max(lcs(S1, S2, m - 1, n), lcs(S1, S2, m, n-1))

In [28]:
import numpy
"""
# Remove X at end of function to run
"""
class Solution:
    """
    Recursion
    Time complexity: O(2^N)
    """
    def longestCommonSubsequenceX(self, text1: str, text2: str) -> int:
        def lcshelper(s1, s2, m, n):
            if m == 0 or n == 0:
                return 0
            if s1[m-1] == s2[n-1]:
                return 1 + lcshelper(s1, s2, m - 1, n - 1)
            return max(lcshelper(s1, s2, m - 1, n), lcshelper(s1, s2, m, n - 1))
        return lcshelper(text1, text2, len(text1), len(text2))
    
    """
    Recursion + memoization solution (top-down approach)
    Time complexity: O(M*N)
    """
    def longestCommonSubsequenceX1(self, text1: str, text2: str) -> int:
        def lcshelper(s1, s2, m, n):
            if m == 0 or n == 0:
                return 0
            if memo[n][m] is None:
                if s1[m-1] == s2[n-1]:
                    memo[n][m] =  1 + lcshelper(s1, s2, m - 1, n - 1)
                else:
                    memo[n][m] = max(lcshelper(s1, s2, m - 1, n), lcshelper(s1, s2, m, n - 1))
            return memo[n][m]
        m = len(text1); n = len(text2)
        memo = [[None for _ in range(m + 1)] for _ in range(n + 1)]
        print(numpy.matrix(memo), end="\n\n")
        return lcshelper(text1, text2, m, n)
    
    
    """
    DP tabulation solution (bottom-up approach)
    Time complexity: O(M*N)
    """
    def longestCommonSubsequence(self, text1: str, text2: str) -> int:
        m = len(text2); n = len(text1);
        dp = [[0 for _ in range(m + 1)] for _ in range(n + 1)]
        
        for i in range(1,n + 1):
            for j in range(1, m + 1):
                if text1[i - 1] == text2[j-1]:
                    dp[i][j] = 1 + dp[i-1][j-1]
                else:
                    dp[i][j] = max(dp[i-1][j], dp[i][j-1])
        print(numpy.matrix(dp), end="\n\n")
        return dp[n][m]
    

import unittest
class LCSTest(unittest.TestCase):
    def test_lcs_test1(self):
        result = Solution().longestCommonSubsequence("abcde","ace")
        self.assertEqual(result, 3)
        
    def test_lcs_test2(self):
        result = Solution().longestCommonSubsequence("abc","abc")
        self.assertEqual(result, 3)
        
    def test_lcs_test3(self):
        result = Solution().longestCommonSubsequence("abc", "def")
        self.assertEqual(result, 0)
        
unittest.main(argv=[''], verbosity=2, exit=False)

test_lcs_test1 (__main__.LCSTest) ... <ipython-input-28-30444b898478>:53: PendingDeprecationWarning: the matrix subclass is not the recommended way to represent matrices or deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Please adjust your code to use regular ndarray.
  print(numpy.matrix(dp), end="\n\n")
ok
test_lcs_test2 (__main__.LCSTest) ... ok
test_lcs_test3 (__main__.LCSTest) ... 

[[0 0 0 0]
 [0 1 1 1]
 [0 1 1 1]
 [0 1 2 2]
 [0 1 2 2]
 [0 1 2 3]]

[[0 0 0 0]
 [0 1 1 1]
 [0 1 2 2]
 [0 1 2 3]]

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]



ok

----------------------------------------------------------------------
Ran 3 tests in 0.005s

OK
