>**Rod Cutting Problem**  


- [Cutting a rod into pieces to maximize Profit](https://www.youtube.com/watch?v=zFe-SX7jzDs&ab_channel=VivekanandKhyade-AlgorithmEveryDay)
- [TECH DOSE EXPLANATION](https://www.youtube.com/watch?v=nYJDp0Hj7M4&list=PLEJXowNB4kPxBwaXtRO1qFLpCzF75DYrS&index=16&ab_channel=TECHDOSE)

Solution using DP tabulation:

    if j > i:
        T[i][j] = T[i-1][j]
    else:
        T[i][j] = Value[i] + T[i][j-i]

In [11]:
import numpy
"""
# Remove X at end of function to run
"""
def maxProfitCuttingRod(pieces, profit, length) -> int: 
    dp = [[0 for _ in range(length + 1)] for _ in range(len(pieces) + 1)]
    for i in range(1, len(pieces) + 1):
        for j in range(1, length + 1):
            if pieces[i - 1] > j: #Exclude
                dp[i][j] = dp[i-1][j]
            else: # Max of excluding or including
                dp[i][j] = max(dp[i-1][j], profit[i-1] + dp[i][j - pieces[i-1]])
    print(numpy.matrix(dp))
    return dp[len(pieces)][length]


def maxProfitCuttingRodX(pieces, profit, length) -> int:
    def cut(pieces, profit, length, N):
        if N == 0 or length == 0:
            return 0
        elif pieces[N-1] > length:
            return cut(pieces, profit, length, N-1)
        else:
            return max(cut(pieces, profit, length, N-1), profit[N-1] +\
                       cut(pieces, profit, length - pieces[N - 1], N))
    return cut(pieces, profit, length, len(pieces))


import unittest
class MaxProfitRodCuttingTest(unittest.TestCase):
    def test_maxprofit_rod_cutting_test1(self):
        result = maxProfitCuttingRod([1,2,3,4,5], [3,5,10,11,15], 5)
        self.assertEqual(result, 16)
        
unittest.main(argv=[''], verbosity=2, exit=False)

test_maxprofit_rod_cutting_test1 (__main__.MaxProfitRodCuttingTest) ... 

[[ 0  0  0  0  0  0]
 [ 0  3  6  9 12 15]
 [ 0  3  6  9 12 15]
 [ 0  3  6 10 13 16]
 [ 0  3  6 10 13 16]
 [ 0  3  6 10 13 16]]


<ipython-input-11-e6fbd39d9714>:13: PendingDeprecationWarning: the matrix subclass is not the recommended way to represent matrices or deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Please adjust your code to use regular ndarray.
  print(numpy.matrix(dp))
ok

----------------------------------------------------------------------
Ran 1 test in 0.003s

OK
