>**Number Of Subset with given difference**

<br>
You are given a list of non-negative integers, a1, a2, ..., an, and a target, S. Now you have 2 symbols + and -. For each integer, you should choose one from + and - as its new symbol.

Find out how many ways to assign symbols to make sum of integers equal to target S.
<br>

 
 - [Another Variation](https://www.youtube.com/watch?v=XP2Y2md89h0&t=1215s&ab_channel=ygongcode)
 

<br>
1.
    $f(x)= \begin{cases}
    F(i-1, j),& \text{if } A(i-1, j) > j\\
    F(i,j) = F(i-1, j) + F(i-1, j-A(i-1)),& \text{else}
\end{cases}
$

Solution:

    Find the number of ways to divide a set into 2 setsets, such that S1 - S2 = target



In [1]:
from typing import List
import numpy
"""
Idea: split the elemts into positive and negative knapsacks

Conditions:
    If array length == 0; return 0
    if sum of array < target or (sum of array + target)%2 != 0: return 0
    
such that :
S1 - S2 = target
S1 - (sum - S1) = target
2S1 = target + sum
S1 = (target + sum)/2

New Goal: Find the number of ways to form a subset S1 from the given set with:
S1 = (target + sum)/2
"""
class Solution:
    def findTargetSumWays(self, nums: List[int], S: int) -> int:
        n = len(nums)
        if n == 0:
            return 0
        
        sumOfArray = sum(nums)
        if sumOfArray < S or (S + sum(nums))%2 != 0:
            return 0
            
        S = (S + sum(nums))//2
        
        dp = [[0 for _ in range(S + 1)] for _ in range(n + 1)]

        """
        - First colum set to True because zero can be formed by taking an empty subset
        """
        for i in range(n + 1):
            dp[i][0] = 1
        print(numpy.matrix(dp), end="\n\n")

        for i in range(1,n + 1):
            for j in range(1, S + 1):
                if nums[i-1] > j:
                    dp[i][j] = dp[i - 1][j]
                else:
                    dp[i][j] = dp[i-1][j] + dp[i-1][j - nums[i-1]]
        print(numpy.matrix(dp), end="\n\n")
        return dp[n][S]



import unittest
class TargetSumTest(unittest.TestCase):
    def test_targetSum_test1(self):
        A = [1, 1, 1, 1, 1]
        result = Solution().findTargetSumWays(A, 3)
        self.assertEqual(result, 5)

    def test_targetSum_test2(self):
        A = [1]
        result = Solution().findTargetSumWays(A, 2)
        self.assertEqual(result, 0)
        
unittest.main(argv=[''], verbosity=2, exit=False)
    

test_targetSum_test1 (__main__.TargetSumTest) ... <ipython-input-1-82fff25822f7>:38: PendingDeprecationWarning: the matrix subclass is not the recommended way to represent matrices or deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Please adjust your code to use regular ndarray.
  print(numpy.matrix(dp), end="\n\n")
<ipython-input-1-82fff25822f7>:46: PendingDeprecationWarning: the matrix subclass is not the recommended way to represent matrices or deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Please adjust your code to use regular ndarray.
  print(numpy.matrix(dp), end="\n\n")
ok
test_targetSum_test2 (__main__.TargetSumTest) ... 

[[1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]]

[[ 1  0  0  0  0]
 [ 1  1  0  0  0]
 [ 1  2  1  0  0]
 [ 1  3  3  1  0]
 [ 1  4  6  4  1]
 [ 1  5 10 10  5]]



ok

----------------------------------------------------------------------
Ran 2 tests in 0.005s

OK


> **Solution using recusion + memoization**

In [35]:
from typing import List

class Solution:
    def findTargetSumWaysRecursive(self, nums: List[int], S: int) -> int:
        memo = {}
        def recursive(nums, index, target, memo):
            if index >= len(nums):
                return 1 if target == 0 else 0
            elif str(index) +"-"+str(target) in memo:
                return memo[str(index) + "-" + str(target)]
            else:
                memo[str(index) +"-"+str(target)] = recursive(nums, index+1, target - nums[index], memo) + \
                recursive(nums, index+1, target + nums[index], memo)
                return memo[str(index) +"-"+str(target)]
        return recursive(nums, 0, S, memo)


import unittest
class TargetSumTest(unittest.TestCase):
    def test_targetSum_findTargetSumWaysRecursive_test1(self):
        A = [1, 1, 1, 1, 1]
        result = Solution().findTargetSumWaysRecursive(A, 3)
        self.assertEqual(result, 5)

    def test_targetSum_findTargetSumWaysRecursive_test2(self):
        A = [1]
        result = Solution().findTargetSumWaysRecursive(A, 2)
        self.assertEqual(result, 0)
        
unittest.main(argv=[''], verbosity=2, exit=False)

test_targetSum_findTargetSumWaysRecursive_test1 (__main__.TargetSumTest) ... ok
test_targetSum_findTargetSumWaysRecursive_test2 (__main__.TargetSumTest) ... ok

----------------------------------------------------------------------
Ran 2 tests in 0.003s

OK


In [30]:
str(0) + "-" + str(10)

'0-10'